version: '3.2'

services:

  db:
    image: postgres
    restart: always
    container_name: postgresDB
    ports:
      - 5432:5432 
    environment:
      POSTGRES_PASSWORD: 12345

  adminer:
    image: adminer
    restart: always
    container_name: adminerServer
    ports:
      - 9080:8080